server {
    listen 8000;
    server_name vps-dashboard.local;
    
    # Temporary
    location = /api/v1/configuration {
        alias /var/www/html/config.json;
        default_type application/json;
    }
}
